/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 01:08:42 GMT 2024
 */

package org.apache.commons.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.nio.CharBuffer;
import org.apache.commons.text.translate.CsvTranslators;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CsvTranslators_ESTest extends CsvTranslators_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      char[] charArray0 = new char[6];
      charArray0[0] = '\"';
      charArray0[5] = 'm';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter();
      csvTranslators_CsvUnescaper0.translateWhole(charBuffer0, stringWriter0);
      assertTrue(charBuffer0.hasRemaining());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      StringWriter stringWriter0 = new StringWriter(1628);
      csvTranslators_CsvUnescaper0.translateWhole("65C", stringWriter0);
      assertEquals("65C", stringWriter0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      char[] charArray0 = new char[6];
      charArray0[0] = '\"';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter(10);
      csvTranslators_CsvUnescaper0.translateWhole(charBuffer0, stringWriter0);
      assertFalse(charBuffer0.isDirect());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      char[] charArray0 = new char[6];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter(0);
      csvTranslators_CsvUnescaper0.translateWhole(charBuffer0, stringWriter0);
      assertEquals(6, charBuffer0.length());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CsvTranslators.CsvEscaper csvTranslators_CsvEscaper0 = new CsvTranslators.CsvEscaper();
      CharBuffer charBuffer0 = CharBuffer.allocate(661);
      StringWriter stringWriter0 = new StringWriter(661);
      // Undeclared exception!
      try { 
        csvTranslators_CsvEscaper0.translateWhole(charBuffer0, stringWriter0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.translate.CsvTranslators$CsvEscaper", e);
      }
  }
}
