/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 01:11:07 GMT 2024
 */

package org.apache.commons.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.translate.JavaUnicodeEscaper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JavaUnicodeEscaper_ESTest extends JavaUnicodeEscaper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.between(0, 1649);
      assertNotNull(javaUnicodeEscaper0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.between((-796), (-796));
      // Undeclared exception!
      try { 
        javaUnicodeEscaper0.toUtf16Escape((-1913));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Not a valid Unicode code point: 0xFFFFF887
         //
         verifyException("java.lang.Character", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.outsideOf(65551, 1905);
      assertNotNull(javaUnicodeEscaper0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = new JavaUnicodeEscaper(2456, 2456, true);
      // Undeclared exception!
      try { 
        javaUnicodeEscaper0.toUtf16Escape(57343);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.commons.text.translate.JavaUnicodeEscaper", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.above((-2786));
      assertNotNull(javaUnicodeEscaper0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.below(65551);
      String string0 = javaUnicodeEscaper0.toUtf16Escape(65551);
      assertEquals("\\uD800\\uDC0F", string0);
  }
}
