/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 01:16:00 GMT 2024
 */

package org.apache.commons.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import java.nio.CharBuffer;
import org.apache.commons.text.translate.OctalUnescaper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OctalUnescaper_ESTest extends OctalUnescaper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[3];
      charArray0[0] = 'k';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 0, (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[3];
      charArray0[2] = '7';
      charArray0[1] = '\\';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 1, (Writer) stringWriter0);
      assertEquals("\u0007", stringWriter0.toString());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      // Undeclared exception!
      try { 
        octalUnescaper0.translate((CharSequence) stringBuffer0, 52, (Writer) stringWriter0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      Writer writer0 = Writer.nullWriter();
      // Undeclared exception!
      try { 
        octalUnescaper0.translate((CharSequence) null, 8, writer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.text.translate.OctalUnescaper", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      char[] charArray0 = new char[10];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      StringWriter stringWriter0 = new StringWriter();
      // Undeclared exception!
      try { 
        octalUnescaper0.translate((CharSequence) charBuffer0, (-912), (Writer) stringWriter0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[5];
      charArray0[1] = '\\';
      charArray0[2] = '0';
      charArray0[3] = '0';
      charArray0[4] = '0';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 1, (Writer) stringWriter0);
      assertEquals("\u0000", stringWriter0.toString());
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[4];
      charArray0[1] = '\\';
      charArray0[2] = '2';
      charArray0[3] = '2';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 1, (Writer) stringWriter0);
      assertEquals("\u0012", stringWriter0.toString());
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[2];
      charArray0[1] = '\\';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 1, (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[7];
      charArray0[1] = '\\';
      charArray0[2] = '5';
      charArray0[3] = '5';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      charBuffer0.append('5');
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 0, (Writer) stringWriter0);
      assertEquals("-", stringWriter0.toString());
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[5];
      charArray0[1] = '\\';
      charArray0[2] = '2';
      charArray0[3] = '2';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 1, (Writer) stringWriter0);
      assertEquals("\u0012", stringWriter0.toString());
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[2];
      charArray0[0] = '\\';
      charArray0[1] = '\\';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 0, (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[5];
      charArray0[1] = '\\';
      charArray0[2] = '2';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 1, (Writer) stringWriter0);
      assertEquals("\u0002", stringWriter0.toString());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      OctalUnescaper octalUnescaper0 = new OctalUnescaper();
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[7];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      int int0 = octalUnescaper0.translate((CharSequence) charBuffer0, 4, (Writer) stringWriter0);
      assertEquals(0, int0);
  }
}
