/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 19:01:59 GMT 2024
 */

package org.apache.commons.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import java.nio.CharBuffer;
import org.apache.commons.text.translate.CsvTranslators;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SinglePassTranslator_ESTest extends SinglePassTranslator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CsvTranslators.CsvEscaper csvTranslators_CsvEscaper0 = new CsvTranslators.CsvEscaper();
      StringWriter stringWriter0 = new StringWriter();
      // Undeclared exception!
      try { 
        csvTranslators_CsvEscaper0.translate((CharSequence) null, 51, (Writer) stringWriter0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CsvEscaper.translate(final CharSequence input, final int index, final Writer out) can not handle a non-zero index.
         //
         verifyException("org.apache.commons.text.translate.SinglePassTranslator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      StringWriter stringWriter0 = new StringWriter();
      int int0 = csvTranslators_CsvUnescaper0.translate((CharSequence) "y0", 0, (Writer) stringWriter0);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      // Undeclared exception!
      try { 
        csvTranslators_CsvUnescaper0.translate((CharSequence) stringBuffer0, 0, (Writer) stringWriter0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      // Undeclared exception!
      try { 
        csvTranslators_CsvUnescaper0.translate((CharSequence) "0", 0, (Writer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.text.translate.CsvTranslators$CsvUnescaper", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      StringWriter stringWriter0 = new StringWriter(0);
      // Undeclared exception!
      try { 
        csvTranslators_CsvUnescaper0.translate((CharSequence) charBuffer0, 0, (Writer) stringWriter0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CsvTranslators.CsvEscaper csvTranslators_CsvEscaper0 = new CsvTranslators.CsvEscaper();
      // Undeclared exception!
      try { 
        csvTranslators_CsvEscaper0.translate((CharSequence) "FFFFFE8B", 0, (Writer) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.translate.CsvTranslators$CsvEscaper", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CsvTranslators.CsvUnescaper csvTranslators_CsvUnescaper0 = new CsvTranslators.CsvUnescaper();
      // Undeclared exception!
      try { 
        csvTranslators_CsvUnescaper0.translate((CharSequence) "FFFFFFFF", (-1), (Writer) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CsvUnescaper.translate(final CharSequence input, final int index, final Writer out) can not handle a non-zero index.
         //
         verifyException("org.apache.commons.text.translate.SinglePassTranslator", e);
      }
  }
}
