/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 00:17:56 GMT 2024
 */

package org.apache.commons.text.lookup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.lookup.AbstractStringLookup;
import org.apache.commons.text.lookup.ConstantStringLookup;
import org.apache.commons.text.lookup.DnsStringLookup;
import org.apache.commons.text.lookup.InterpolatorStringLookup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AbstractStringLookup_ESTest extends AbstractStringLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InterpolatorStringLookup interpolatorStringLookup0 = new InterpolatorStringLookup();
      // Undeclared exception!
      try { 
        interpolatorStringLookup0.substringAfter("Kp^x%2$", "=H8cU&yHsL`%otrCk");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.AbstractStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = AbstractStringLookup.toLookupKey("xb;MHIf", "1S");
      assertEquals("xb;MHIf:1S", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = AbstractStringLookup.toLookupKey(" 0&/2DaypMX\tdu^{W", "", "mQ6XrXJlsk");
      assertEquals(" 0&/2DaypMX\tdu^{WmQ6XrXJlsk", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = AbstractStringLookup.toLookupKey("", "", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ConstantStringLookup constantStringLookup0 = new ConstantStringLookup();
      // Undeclared exception!
      try { 
        constantStringLookup0.substringAfter(" 0&/2DaypMX\tdu^{WmQ6XrXJlsk", '%');
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.AbstractStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DnsStringLookup dnsStringLookup0 = DnsStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        dnsStringLookup0.substringAfterLast("h0h-(u0]s=TMq,JO", '');
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.AbstractStringLookup", e);
      }
  }
}
