/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 17:53:11 GMT 2024
 */

package org.apache.commons.text.lookup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.lookup.DateStringLookup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DateStringLookup_ESTest extends DateStringLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DateStringLookup dateStringLookup0 = DateStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        dateStringLookup0.lookup((String) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/time/FastDateFormat
         //
         verifyException("org.apache.commons.text.lookup.DateStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DateStringLookup dateStringLookup0 = DateStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        dateStringLookup0.lookup("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/time/FastDateFormat
         //
         verifyException("org.apache.commons.text.lookup.DateStringLookup", e);
      }
  }
}
