/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 00:30:55 GMT 2024
 */

package org.apache.commons.text.lookup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.lookup.JavaPlatformStringLookup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JavaPlatformStringLookup_ESTest extends JavaPlatformStringLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      String string0 = javaPlatformStringLookup0.getVirtualMachine();
      assertEquals("OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      String string0 = javaPlatformStringLookup0.getRuntime();
      assertEquals("OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04) from Ubuntu", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        javaPlatformStringLookup0.getOperatingSystem();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.JavaPlatformStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        javaPlatformStringLookup0.getHardware();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.JavaPlatformStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      String string0 = javaPlatformStringLookup0.lookup("runtime");
      assertEquals("OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04) from Ubuntu", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      String string0 = javaPlatformStringLookup0.lookup("vm");
      assertEquals("OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      String string0 = javaPlatformStringLookup0.lookup("version");
      assertEquals("Java version 11.0.21", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        javaPlatformStringLookup0.lookup("os");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.JavaPlatformStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        javaPlatformStringLookup0.lookup("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 
         //
         verifyException("org.apache.commons.text.lookup.JavaPlatformStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      String string0 = javaPlatformStringLookup0.lookup("locale");
      assertEquals("default locale: en, platform encoding: UTF-8", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      String string0 = javaPlatformStringLookup0.lookup((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        javaPlatformStringLookup0.lookup("hardware");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.JavaPlatformStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JavaPlatformStringLookup javaPlatformStringLookup0 = JavaPlatformStringLookup.INSTANCE;
      String string0 = javaPlatformStringLookup0.getLocale();
      assertEquals("default locale: en, platform encoding: UTF-8", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[9];
      // Undeclared exception!
      try { 
        JavaPlatformStringLookup.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.JavaPlatformStringLookup", e);
      }
  }
}
