/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 00:38:55 GMT 2024
 */

package org.apache.commons.text.lookup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.UnsupportedEncodingException;
import org.apache.commons.text.lookup.UrlDecoderStringLookup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UrlDecoderStringLookup_ESTest extends UrlDecoderStringLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UrlDecoderStringLookup urlDecoderStringLookup0 = UrlDecoderStringLookup.INSTANCE;
      String string0 = urlDecoderStringLookup0.lookup("6kCT<zU");
      assertEquals("6kCT<zU", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UrlDecoderStringLookup urlDecoderStringLookup0 = UrlDecoderStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        urlDecoderStringLookup0.lookup("%s: source=%s, encoding=%s");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: \"s:\"
         //
         verifyException("java.net.URLDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UrlDecoderStringLookup urlDecoderStringLookup0 = UrlDecoderStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        urlDecoderStringLookup0.decode("uEm!GOB?OdyHM)en", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UrlDecoderStringLookup urlDecoderStringLookup0 = UrlDecoderStringLookup.INSTANCE;
      try { 
        urlDecoderStringLookup0.decode("f;", "");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(UnsupportedEncodingException e) {
         //
         // URLDecoder: empty string enc parameter
         //
         verifyException("java.net.URLDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UrlDecoderStringLookup urlDecoderStringLookup0 = UrlDecoderStringLookup.INSTANCE;
      String string0 = urlDecoderStringLookup0.lookup((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UrlDecoderStringLookup urlDecoderStringLookup0 = UrlDecoderStringLookup.INSTANCE;
      String string0 = urlDecoderStringLookup0.lookup("");
      assertNotNull(string0);
      assertEquals("", string0);
  }
}
