/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 00:40:06 GMT 2024
 */

package org.apache.commons.text.lookup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.UnsupportedEncodingException;
import org.apache.commons.text.lookup.UrlEncoderStringLookup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UrlEncoderStringLookup_ESTest extends UrlEncoderStringLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UrlEncoderStringLookup urlEncoderStringLookup0 = UrlEncoderStringLookup.INSTANCE;
      String string0 = urlEncoderStringLookup0.lookup("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UrlEncoderStringLookup urlEncoderStringLookup0 = UrlEncoderStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        urlEncoderStringLookup0.encode((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // charsetName
         //
         verifyException("java.net.URLEncoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UrlEncoderStringLookup urlEncoderStringLookup0 = UrlEncoderStringLookup.INSTANCE;
      try { 
        urlEncoderStringLookup0.encode("^|s8ja-8DXRE!y", "9%21b");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(UnsupportedEncodingException e) {
         //
         // 9%21b
         //
         verifyException("java.net.URLEncoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UrlEncoderStringLookup urlEncoderStringLookup0 = UrlEncoderStringLookup.INSTANCE;
      String string0 = urlEncoderStringLookup0.lookup((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UrlEncoderStringLookup urlEncoderStringLookup0 = UrlEncoderStringLookup.INSTANCE;
      String string0 = urlEncoderStringLookup0.lookup("CNLHz9\"V@");
      assertEquals("CNLHz%7F9%22V%40", string0);
      assertNotNull(string0);
  }
}
