/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 18:11:52 GMT 2024
 */

package org.apache.commons.text.lookup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.lookup.UrlStringLookup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UrlStringLookup_ESTest extends UrlStringLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UrlStringLookup urlStringLookup0 = UrlStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        urlStringLookup0.lookup("&P:-d");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.UrlStringLookup", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UrlStringLookup urlStringLookup0 = UrlStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        urlStringLookup0.lookup("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Bad URL key format []; expected format is DocumentPath:Key.
         //
         verifyException("org.apache.commons.text.lookup.IllegalArgumentExceptions", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UrlStringLookup urlStringLookup0 = UrlStringLookup.INSTANCE;
      String string0 = urlStringLookup0.lookup((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UrlStringLookup urlStringLookup0 = UrlStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        urlStringLookup0.lookup("&P:-d&P:-d~");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.lookup.UrlStringLookup", e);
      }
  }
}
