/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 00:42:24 GMT 2024
 */

package org.apache.commons.text.lookup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.lookup.XmlDecoderStringLookup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class XmlDecoderStringLookup_ESTest extends XmlDecoderStringLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlDecoderStringLookup xmlDecoderStringLookup0 = XmlDecoderStringLookup.INSTANCE;
      // Undeclared exception!
      try { 
        xmlDecoderStringLookup0.lookup("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.commons.text.StringEscapeUtils
         //
         verifyException("org.apache.commons.text.lookup.XmlDecoderStringLookup", e);
      }
  }
}
