/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 18:14:05 GMT 2024
 */

package org.apache.commons.text.lookup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.lookup.XmlEncoderStringLookup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class XmlEncoderStringLookup_ESTest extends XmlEncoderStringLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlEncoderStringLookup xmlEncoderStringLookup0 = new XmlEncoderStringLookup();
      // Undeclared exception!
      try { 
        xmlEncoderStringLookup0.lookup("&yacute;");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.commons.text.StringEscapeUtils
         //
         verifyException("org.apache.commons.text.lookup.XmlEncoderStringLookup", e);
      }
  }
}
