/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 17:48:34 GMT 2024
 */

package org.apache.commons.text.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.PipedReader;
import org.apache.commons.text.StringSubstitutor;
import org.apache.commons.text.io.StringSubstitutorReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StringSubstitutorReader_ESTest extends StringSubstitutorReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PipedReader pipedReader0 = new PipedReader();
      StringSubstitutorReader stringSubstitutorReader0 = null;
      try {
        stringSubstitutorReader0 = new StringSubstitutorReader(pipedReader0, (StringSubstitutor) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.apache.commons.text.StringSubstitutor
         //
         verifyException("org.apache.commons.text.io.StringSubstitutorReader", e);
      }
  }
}
