/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 18:22:33 GMT 2024
 */

package org.apache.commons.text.similarity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.text.similarity.CosineDistance;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CosineDistance_ESTest extends CosineDistance_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CosineDistance cosineDistance0 = new CosineDistance();
      CharBuffer charBuffer0 = CharBuffer.allocate(543);
      // Undeclared exception!
      try { 
        cosineDistance0.apply((CharSequence) null, charBuffer0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.similarity.RegexTokenizer", e);
      }
  }
}
