/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 18:28:38 GMT 2024
 */

package org.apache.commons.text.similarity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.text.similarity.HammingDistance;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HammingDistance_ESTest extends HammingDistance_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HammingDistance hammingDistance0 = new HammingDistance();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      char[] charArray0 = new char[3];
      charArray0[1] = ';';
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0, 1, 1);
      Integer integer0 = hammingDistance0.apply(charBuffer0, charBuffer1);
      assertEquals(1, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HammingDistance hammingDistance0 = new HammingDistance();
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = charBuffer0.slice();
      charBuffer1.limit(0);
      // Undeclared exception!
      try { 
        hammingDistance0.apply(charBuffer0, charBuffer1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must have the same length
         //
         verifyException("org.apache.commons.text.similarity.HammingDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HammingDistance hammingDistance0 = new HammingDistance();
      char[] charArray0 = new char[1];
      charArray0[0] = '/';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.allocate(1);
      Integer integer0 = hammingDistance0.apply(charBuffer0, charBuffer1);
      assertEquals(1, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HammingDistance hammingDistance0 = new HammingDistance();
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0, 0, 0);
      // Undeclared exception!
      try { 
        hammingDistance0.apply(charBuffer1, charBuffer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must have the same length
         //
         verifyException("org.apache.commons.text.similarity.HammingDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HammingDistance hammingDistance0 = new HammingDistance();
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      // Undeclared exception!
      try { 
        hammingDistance0.apply(charBuffer0, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.HammingDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HammingDistance hammingDistance0 = new HammingDistance();
      CharBuffer charBuffer0 = CharBuffer.allocate(3535);
      hammingDistance0.apply(charBuffer0, charBuffer0);
      hammingDistance0.apply(charBuffer0, charBuffer0);
      // Undeclared exception!
      hammingDistance0.apply(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      HammingDistance hammingDistance0 = new HammingDistance();
      // Undeclared exception!
      try { 
        hammingDistance0.apply((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.HammingDistance", e);
      }
  }
}
