/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 01:35:58 GMT 2024
 */

package org.apache.commons.text.similarity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.similarity.IntersectionResult;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IntersectionResult_ESTest extends IntersectionResult_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(891, 891, 891);
      IntersectionResult intersectionResult1 = new IntersectionResult(891, 891, 18);
      boolean boolean0 = intersectionResult1.equals(intersectionResult0);
      assertEquals(891, intersectionResult1.getSizeA());
      assertEquals(891, intersectionResult1.getSizeB());
      assertFalse(intersectionResult0.equals((Object)intersectionResult1));
      assertFalse(boolean0);
      assertEquals(18, intersectionResult1.getIntersection());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(0, 0, 0);
      IntersectionResult intersectionResult1 = new IntersectionResult(0, 1894, 0);
      boolean boolean0 = intersectionResult0.equals(intersectionResult1);
      assertEquals(1894, intersectionResult1.getSizeB());
      assertEquals(0, intersectionResult1.getSizeA());
      assertFalse(boolean0);
      assertFalse(intersectionResult1.equals((Object)intersectionResult0));
      assertEquals(0, intersectionResult1.getIntersection());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(0, 0, 0);
      IntersectionResult intersectionResult1 = new IntersectionResult(17, 0, 0);
      boolean boolean0 = intersectionResult0.equals(intersectionResult1);
      assertFalse(boolean0);
      assertFalse(intersectionResult1.equals((Object)intersectionResult0));
      assertEquals(17, intersectionResult1.getSizeA());
      assertEquals(0, intersectionResult1.getSizeB());
      assertEquals(0, intersectionResult1.getIntersection());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IntersectionResult intersectionResult0 = null;
      try {
        intersectionResult0 = new IntersectionResult((-178), (-1), (-178));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Set size |A| is not positive: -178
         //
         verifyException("org.apache.commons.text.similarity.IntersectionResult", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(0, 1, 0);
      int int0 = intersectionResult0.getSizeB();
      assertEquals(1, int0);
      assertEquals(0, intersectionResult0.getSizeA());
      assertEquals(0, intersectionResult0.getIntersection());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(721, 721, 721);
      int int0 = intersectionResult0.getSizeA();
      assertEquals(721, intersectionResult0.getIntersection());
      assertEquals(721, intersectionResult0.getSizeB());
      assertEquals(721, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(2412, 2412, 2412);
      int int0 = intersectionResult0.getIntersection();
      assertEquals(2412, intersectionResult0.getSizeB());
      assertEquals(2412, intersectionResult0.getSizeA());
      assertEquals(2412, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(2572, 2572, 2572);
      IntersectionResult intersectionResult1 = new IntersectionResult(2572, 2572, 2166);
      boolean boolean0 = intersectionResult0.equals(intersectionResult1);
      assertFalse(intersectionResult1.equals((Object)intersectionResult0));
      assertFalse(boolean0);
      assertEquals(2572, intersectionResult1.getSizeA());
      assertEquals(2572, intersectionResult1.getSizeB());
      assertEquals(2572, intersectionResult0.getIntersection());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(0, 0, 0);
      IntersectionResult intersectionResult1 = new IntersectionResult(0, 1, 0);
      boolean boolean0 = intersectionResult1.equals(intersectionResult0);
      assertFalse(intersectionResult0.equals((Object)intersectionResult1));
      assertEquals(0, intersectionResult1.getSizeA());
      assertEquals(1, intersectionResult1.getSizeB());
      assertFalse(boolean0);
      assertEquals(0, intersectionResult1.getIntersection());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(721, 721, 721);
      IntersectionResult intersectionResult1 = new IntersectionResult(1573, 1573, 721);
      boolean boolean0 = intersectionResult1.equals(intersectionResult0);
      assertEquals(721, intersectionResult1.getIntersection());
      assertEquals(1573, intersectionResult1.getSizeB());
      assertEquals(1573, intersectionResult1.getSizeA());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(2, 2, 2);
      Object object0 = new Object();
      boolean boolean0 = intersectionResult0.equals(object0);
      assertEquals(2, intersectionResult0.getSizeB());
      assertEquals(2, intersectionResult0.getSizeA());
      assertEquals(2, intersectionResult0.getIntersection());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(2579, 2579, 2579);
      boolean boolean0 = intersectionResult0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(2579, intersectionResult0.getSizeB());
      assertEquals(2579, intersectionResult0.getSizeA());
      assertEquals(2579, intersectionResult0.getIntersection());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(716, 716, 716);
      boolean boolean0 = intersectionResult0.equals(intersectionResult0);
      assertTrue(boolean0);
      assertEquals(716, intersectionResult0.getSizeB());
      assertEquals(716, intersectionResult0.getSizeA());
      assertEquals(716, intersectionResult0.getIntersection());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(2572, 2572, 2572);
      IntersectionResult intersectionResult1 = new IntersectionResult(2572, 2572, 2572);
      boolean boolean0 = intersectionResult1.equals(intersectionResult0);
      assertEquals(2572, intersectionResult1.getSizeB());
      assertEquals(2572, intersectionResult1.getSizeA());
      assertTrue(boolean0);
      assertEquals(2572, intersectionResult1.getIntersection());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      IntersectionResult intersectionResult0 = null;
      try {
        intersectionResult0 = new IntersectionResult(0, 0, 3019);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid intersection of A and B: 3019
         //
         verifyException("org.apache.commons.text.similarity.IntersectionResult", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IntersectionResult intersectionResult0 = null;
      try {
        intersectionResult0 = new IntersectionResult(0, 0, (-126));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid intersection of A and B: -126
         //
         verifyException("org.apache.commons.text.similarity.IntersectionResult", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      IntersectionResult intersectionResult0 = null;
      try {
        intersectionResult0 = new IntersectionResult(0, (-292), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Set size |B| is not positive: -292
         //
         verifyException("org.apache.commons.text.similarity.IntersectionResult", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      IntersectionResult intersectionResult0 = null;
      try {
        intersectionResult0 = new IntersectionResult((-386), (-386), (-690));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Set size |A| is not positive: -386
         //
         verifyException("org.apache.commons.text.similarity.IntersectionResult", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(0, 0, 0);
      String string0 = intersectionResult0.toString();
      assertEquals("Size A: 0, Size B: 0, Intersection: 0", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(0, 0, 0);
      int int0 = intersectionResult0.getSizeB();
      assertEquals(0, intersectionResult0.getSizeA());
      assertEquals(0, int0);
      assertEquals(0, intersectionResult0.getIntersection());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(0, 0, 0);
      int int0 = intersectionResult0.getIntersection();
      assertEquals(0, intersectionResult0.getSizeB());
      assertEquals(0, intersectionResult0.getSizeA());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(0, 0, 0);
      int int0 = intersectionResult0.getSizeA();
      assertEquals(0, intersectionResult0.getSizeB());
      assertEquals(0, intersectionResult0.getIntersection());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      IntersectionResult intersectionResult0 = new IntersectionResult(2572, 2572, 2572);
      intersectionResult0.hashCode();
      assertEquals(2572, intersectionResult0.getSizeA());
      assertEquals(2572, intersectionResult0.getSizeB());
      assertEquals(2572, intersectionResult0.getIntersection());
  }
}
