/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 18:33:38 GMT 2024
 */

package org.apache.commons.text.similarity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.text.similarity.JaccardSimilarity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JaccardSimilarity_ESTest extends JaccardSimilarity_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JaccardSimilarity jaccardSimilarity0 = new JaccardSimilarity();
      CharBuffer charBuffer0 = CharBuffer.allocate(3390);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 726, 3390);
      Double double0 = jaccardSimilarity0.apply(charBuffer0, charBuffer1);
      assertEquals(1.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JaccardSimilarity jaccardSimilarity0 = JaccardSimilarity.INSTANCE;
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      charBuffer0.get();
      // Undeclared exception!
      try { 
        jaccardSimilarity0.apply(charBuffer1, charBuffer1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JaccardSimilarity jaccardSimilarity0 = JaccardSimilarity.INSTANCE;
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.allocate(0);
      Double double0 = jaccardSimilarity0.apply(charBuffer0, charBuffer1);
      assertEquals(0.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JaccardSimilarity jaccardSimilarity0 = new JaccardSimilarity();
      CharBuffer charBuffer0 = CharBuffer.allocate(2986);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 1);
      Double double0 = jaccardSimilarity0.apply(charBuffer1, charBuffer0);
      assertEquals(0.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JaccardSimilarity jaccardSimilarity0 = new JaccardSimilarity();
      CharBuffer charBuffer0 = CharBuffer.allocate(2986);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 1);
      Double double0 = jaccardSimilarity0.apply(charBuffer1, charBuffer1);
      assertEquals(1.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JaccardSimilarity jaccardSimilarity0 = new JaccardSimilarity();
      CharBuffer charBuffer0 = CharBuffer.allocate(2986);
      // Undeclared exception!
      try { 
        jaccardSimilarity0.apply(charBuffer0, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Input cannot be null
         //
         verifyException("org.apache.commons.text.similarity.JaccardSimilarity", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JaccardSimilarity jaccardSimilarity0 = new JaccardSimilarity();
      CharBuffer charBuffer0 = CharBuffer.allocate(2986);
      jaccardSimilarity0.apply(charBuffer0, charBuffer0);
      jaccardSimilarity0.apply(charBuffer0, charBuffer0);
      jaccardSimilarity0.apply(charBuffer0, charBuffer0);
      // Undeclared exception!
      jaccardSimilarity0.apply(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JaccardSimilarity jaccardSimilarity0 = new JaccardSimilarity();
      // Undeclared exception!
      try { 
        jaccardSimilarity0.apply((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Input cannot be null
         //
         verifyException("org.apache.commons.text.similarity.JaccardSimilarity", e);
      }
  }
}
