/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 01:42:15 GMT 2024
 */

package org.apache.commons.text.similarity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.text.similarity.JaroWinklerSimilarity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JaroWinklerSimilarity_ESTest extends JaroWinklerSimilarity_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JaroWinklerSimilarity jaroWinklerSimilarity0 = JaroWinklerSimilarity.INSTANCE;
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      char[] charArray0 = new char[8];
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0, 0, 0);
      // Undeclared exception!
      try { 
        jaroWinklerSimilarity0.apply(charBuffer0, charBuffer1);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.apache.commons.text.similarity.JaroWinklerSimilarity", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      char[] charArray1 = new char[22];
      charArray1[1] = 'T';
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray1);
      int[] intArray0 = JaroWinklerSimilarity.matches(charBuffer0, charBuffer1);
      assertArrayEquals(new int[] {5, 0, 1}, intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      char[] charArray1 = new char[3];
      charArray1[0] = 'M';
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray1);
      int[] intArray0 = JaroWinklerSimilarity.matches(charBuffer1, charBuffer0);
      assertArrayEquals(new int[] {2, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(2154);
      // Undeclared exception!
      JaroWinklerSimilarity.matches(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        JaroWinklerSimilarity.matches((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.text.similarity.JaroWinklerSimilarity", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(96);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      charBuffer0.append((CharSequence) charBuffer1);
      // Undeclared exception!
      try { 
        JaroWinklerSimilarity.matches(charBuffer1, charBuffer1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      char[] charArray0 = new char[6];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      JaroWinklerSimilarity jaroWinklerSimilarity0 = new JaroWinklerSimilarity();
      // Undeclared exception!
      try { 
        jaroWinklerSimilarity0.apply(charBuffer0, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.JaroWinklerSimilarity", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JaroWinklerSimilarity jaroWinklerSimilarity0 = JaroWinklerSimilarity.INSTANCE;
      // Undeclared exception!
      try { 
        jaroWinklerSimilarity0.apply((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.JaroWinklerSimilarity", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      char[] charArray1 = new char[22];
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray1);
      int[] intArray0 = JaroWinklerSimilarity.matches(charBuffer1, charBuffer0);
      assertArrayEquals(new int[] {5, 0, 4}, intArray0);
  }
}
