/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 01:43:42 GMT 2024
 */

package org.apache.commons.text.similarity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.text.similarity.LevenshteinDetailedDistance;
import org.apache.commons.text.similarity.LevenshteinResults;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LevenshteinDetailedDistance_ESTest extends LevenshteinDetailedDistance_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = LevenshteinDetailedDistance.getDefaultInstance();
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 1);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer1, charBuffer0);
      assertEquals(1, (int)levenshteinResults0.getInsertCount());
      assertEquals(1, (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(599);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      CharBuffer charBuffer0 = CharBuffer.allocate(599);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 599, 599);
      charBuffer0.put('9');
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, charBuffer1);
      assertEquals(598, (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(598, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = Integer.getInteger("", 3);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("", "");
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer(599);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      Integer integer1 = levenshteinDetailedDistance0.getThreshold();
      assertEquals(599, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      Integer integer0 = levenshteinDetailedDistance0.getThreshold();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      CharBuffer charBuffer0 = CharBuffer.allocate(571);
      // Undeclared exception!
      levenshteinDetailedDistance0.apply(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      char[] charArray0 = new char[2];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      Integer integer0 = new Integer(2981);
      charBuffer0.get(charArray0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply(charBuffer1, charBuffer1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Integer integer0 = new Integer((-1355));
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = null;
      try {
        levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Threshold must not be negative
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(599);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 1);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = LevenshteinDetailedDistance.getDefaultInstance();
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, charBuffer1);
      assertEquals(599, (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals(599, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      char[] charArray0 = new char[2];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      Integer integer0 = new Integer(1);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, "X");
      assertEquals((-1), (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = Integer.getInteger("X9H6?jeHuv4=tF%N/4", 3);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("X9H6?jeHuv4=tF%N/4", "X9H6?jeHuv4=tF%N/4");
      assertEquals(0, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = Integer.getInteger("org.apache.commons.text.similarity.LevenshteinDetailedDistance", 0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("X", "org.apache.commons.text.similarity.LevenshteinDetailedDistance");
      assertEquals((-1), (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = Integer.getInteger(", Insert: ", Integer.MAX_VALUE);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(", Insert: ", ", Insert: ");
      assertEquals(0, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer(1);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("X", charBuffer0);
      assertEquals(1, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(1, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(2);
      Integer integer0 = new Integer(2);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, "");
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(2, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals(2, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      char[] charArray0 = new char[0];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      Integer integer0 = new Integer(1);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("k][8&zOe^],K", charBuffer0);
      assertEquals((-1), (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = Integer.getInteger("", 0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("", "N");
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals((-1), (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer(599);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      CharBuffer charBuffer0 = CharBuffer.allocate(599);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 1);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer1, charBuffer0);
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(599, (int)levenshteinResults0.getInsertCount());
      assertEquals(599, (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Integer integer0 = Integer.getInteger("", 3112);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply("", (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      char[] charArray0 = new char[22];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, "org.apache.commons.text.similarity.LevenshteinDetailedDistance");
      assertEquals(22, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(62, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      char[] charArray0 = new char[4];
      charArray0[3] = '^';
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = LevenshteinDetailedDistance.getDefaultInstance();
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.allocate(1);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, charBuffer1);
      assertEquals(3, (int)levenshteinResults0.getDistance());
      assertEquals(3, (int)levenshteinResults0.getDeleteCount());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Integer integer0 = Integer.getInteger("X", 0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      Integer integer1 = levenshteinDetailedDistance0.getThreshold();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = LevenshteinDetailedDistance.getDefaultInstance();
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply("", (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }
}
