/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 18:37:29 GMT 2024
 */

package org.apache.commons.text.similarity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.text.similarity.LevenshteinDetailedDistance;
import org.apache.commons.text.similarity.LevenshteinResults;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LevenshteinDetailedDistance_ESTest extends LevenshteinDetailedDistance_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 0, 0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer1, charBuffer0);
      assertEquals(1, (int)levenshteinResults0.getDistance());
      assertEquals(1, (int)levenshteinResults0.getInsertCount());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(1);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      char[] charArray0 = new char[2];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 0, 1);
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer0, 0, 0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer1, charBuffer2);
      assertEquals(1, (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(1, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer(2799);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("", "hi@Vb/ik^gZz5X");
      assertEquals(16, (int)levenshteinResults0.getInsertCount());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(16, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer(2356);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      Integer integer1 = levenshteinDetailedDistance0.getThreshold();
      assertEquals(2356, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(250);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      // Undeclared exception!
      levenshteinDetailedDistance0.apply(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Integer integer0 = new Integer((-800));
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = null;
      try {
        levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Threshold must not be negative
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      char[] charArray0 = new char[6];
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = LevenshteinDetailedDistance.getDefaultInstance();
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer1, charBuffer0);
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals(6, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(6, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply("p.Yf_T\"", (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("(v2i,{", "pYfZnJ");
      assertEquals((-1), (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("p.YfZn\"", "hi@Vb/ik^gZz5X");
      assertEquals((-1), (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer(Integer.MAX_VALUE);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("p.Yf_T\"", "p.Yf_T\"");
      assertEquals(0, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      char[] charArray0 = new char[2];
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0);
      Integer integer0 = new Integer(3);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer1, charBuffer0);
      assertEquals(2, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(2, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(226);
      Integer integer0 = new Integer(226);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, "@=");
      assertEquals(2, (int)levenshteinResults0.getSubstituteCount());
      assertEquals(226, (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, charBuffer0);
      assertEquals(0, (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer(1);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      char[] charArray0 = new char[2];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0, 2, 0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer1, charBuffer0);
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals((-1), (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
      assertEquals(0, (int)levenshteinResults0.getSubstituteCount());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply(charBuffer0, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = Integer.getInteger("A`7w}6b$12", 0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("A`7w}6b$12", "");
      assertEquals((-1), (int)levenshteinResults0.getDistance());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer(53);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      // Undeclared exception!
      try { 
        levenshteinDetailedDistance0.apply((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CharSequences must not be null
         //
         verifyException("org.apache.commons.text.similarity.LevenshteinDetailedDistance", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("p.Yf_T\"", "(xY=m#");
      assertEquals(0, (int)levenshteinResults0.getInsertCount());
      assertEquals(5, (int)levenshteinResults0.getSubstituteCount());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      char[] charArray0 = new char[5];
      charArray0[0] = '6';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = LevenshteinDetailedDistance.getDefaultInstance();
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply(charBuffer0, "A`7w}6b$12");
      assertEquals(9, (int)levenshteinResults0.getDistance());
      assertEquals(0, (int)levenshteinResults0.getDeleteCount());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Integer integer0 = Integer.getInteger("A`7w}6b$12", 0);
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance(integer0);
      Integer integer1 = levenshteinDetailedDistance0.getThreshold();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = new LevenshteinDetailedDistance();
      LevenshteinResults levenshteinResults0 = levenshteinDetailedDistance0.apply("N@R!Mm5$8q+JpbH0-Q", "p.YfZn\"");
      assertEquals(18, (int)levenshteinResults0.getDistance());
      assertEquals(7, (int)levenshteinResults0.getSubstituteCount());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LevenshteinDetailedDistance levenshteinDetailedDistance0 = LevenshteinDetailedDistance.getDefaultInstance();
      Integer integer0 = levenshteinDetailedDistance0.getThreshold();
      assertNull(integer0);
  }
}
