/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 15 01:48:55 GMT 2024
 */

package org.apache.commons.text.similarity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.text.similarity.LongestCommonSubsequence;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LongestCommonSubsequence_ESTest extends LongestCommonSubsequence_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      int[][] intArray0 = longestCommonSubsequence0.longestCommonSubstringLengthArray("%&pk.$D", "%&pk.$D");
      assertEquals(8, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      CharBuffer charBuffer0 = CharBuffer.allocate('p');
      Integer integer0 = longestCommonSubsequence0.apply(charBuffer0, "Xp\u0000\u0000\u0000");
      assertEquals(3, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      CharBuffer charBuffer0 = CharBuffer.allocate(2);
      char[] charArray0 = new char[3];
      charArray0[1] = 'M';
      charArray0[2] = 'o';
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0);
      CharSequence charSequence0 = longestCommonSubsequence0.longestCommonSubsequence(charBuffer1, charBuffer0);
      assertEquals("\u0000", charSequence0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[5];
      charArray0[0] = 'X';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharSequence charSequence0 = longestCommonSubsequence0.longestCommonSubsequence(charBuffer0, charBuffer0);
      assertEquals("X\u0000\u0000\u0000\u0000", charSequence0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0, 0, 0);
      CharSequence charSequence0 = longestCommonSubsequence0.logestCommonSubsequence(charBuffer0, charBuffer1);
      assertEquals("", charSequence0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = LongestCommonSubsequence.INSTANCE;
      CharBuffer charBuffer0 = CharBuffer.allocate(267);
      // Undeclared exception!
      longestCommonSubsequence0.longestCommonSubstringLengthArray(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      // Undeclared exception!
      try { 
        longestCommonSubsequence0.longestCommonSubstringLengthArray((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      CharBuffer charBuffer0 = CharBuffer.allocate(493);
      // Undeclared exception!
      longestCommonSubsequence0.longestCommonSubsequence(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = LongestCommonSubsequence.INSTANCE;
      CharBuffer charBuffer0 = CharBuffer.allocate(1705);
      // Undeclared exception!
      longestCommonSubsequence0.logestCommonSubsequence(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      CharBuffer charBuffer0 = CharBuffer.allocate(2482);
      // Undeclared exception!
      longestCommonSubsequence0.apply(charBuffer0, charBuffer0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      // Undeclared exception!
      try { 
        longestCommonSubsequence0.longestCommonSubsequence((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Inputs must not be null
         //
         verifyException("org.apache.commons.text.similarity.LongestCommonSubsequence", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      int[][] intArray0 = longestCommonSubsequence0.longestCommonSubstringLengthArray("w", charBuffer0);
      assertEquals(2, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = LongestCommonSubsequence.INSTANCE;
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      char[] charArray0 = new char[1];
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0);
      CharSequence charSequence0 = longestCommonSubsequence0.longestCommonSubsequence(charBuffer1, charBuffer0);
      assertEquals("", charSequence0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = LongestCommonSubsequence.INSTANCE;
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      CharSequence charSequence0 = longestCommonSubsequence0.longestCommonSubsequence(charBuffer0, "");
      assertEquals("", charSequence0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      // Undeclared exception!
      try { 
        longestCommonSubsequence0.longestCommonSubsequence("", (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Inputs must not be null
         //
         verifyException("org.apache.commons.text.similarity.LongestCommonSubsequence", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      // Undeclared exception!
      try { 
        longestCommonSubsequence0.logestCommonSubsequence((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Inputs must not be null
         //
         verifyException("org.apache.commons.text.similarity.LongestCommonSubsequence", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[6];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      Integer integer0 = longestCommonSubsequence0.apply("\u0000", charBuffer0);
      assertEquals(1, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = LongestCommonSubsequence.INSTANCE;
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      char[] charArray0 = new char[1];
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0);
      Integer integer0 = longestCommonSubsequence0.apply(charBuffer1, charBuffer0);
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      Integer integer0 = longestCommonSubsequence0.apply(charBuffer0, charBuffer0);
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      char[] charArray0 = new char[0];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      LongestCommonSubsequence longestCommonSubsequence0 = LongestCommonSubsequence.INSTANCE;
      // Undeclared exception!
      try { 
        longestCommonSubsequence0.apply(charBuffer0, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Inputs must not be null
         //
         verifyException("org.apache.commons.text.similarity.LongestCommonSubsequence", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      // Undeclared exception!
      try { 
        longestCommonSubsequence0.apply((CharSequence) null, (CharSequence) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Inputs must not be null
         //
         verifyException("org.apache.commons.text.similarity.LongestCommonSubsequence", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[1];
      charArray0[0] = 'w';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.allocate(880);
      CharSequence charSequence0 = longestCommonSubsequence0.longestCommonSubsequence(charBuffer0, charBuffer1);
      assertEquals("", charSequence0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharSequence charSequence0 = longestCommonSubsequence0.logestCommonSubsequence(charBuffer0, charBuffer0);
      assertEquals("\u0000\u0000\u0000\u0000\u0000", charSequence0);
  }
}
