/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 17:38:53 GMT 2024
 */

package org.apache.commons.text.diff;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.diff.CommandVisitor;
import org.apache.commons.text.diff.InsertCommand;
import org.apache.commons.text.diff.KeepCommand;
import org.apache.commons.text.diff.ReplacementsFinder;
import org.apache.commons.text.diff.ReplacementsHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EditCommand_ESTest extends EditCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KeepCommand<Object> keepCommand0 = new KeepCommand<Object>((Object) null);
      ReplacementsHandler<Object> replacementsHandler0 = (ReplacementsHandler<Object>) mock(ReplacementsHandler.class, new ViolatedAssumptionAnswer());
      ReplacementsFinder<Object> replacementsFinder0 = new ReplacementsFinder<Object>(replacementsHandler0);
      keepCommand0.accept(replacementsFinder0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      KeepCommand<Object> keepCommand0 = new KeepCommand<Object>((Object) null);
      Object object0 = keepCommand0.getObject();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object object0 = new Object();
      KeepCommand<Object> keepCommand0 = new KeepCommand<Object>(object0);
      Object object1 = keepCommand0.getObject();
      assertSame(object1, object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Object object0 = new Object();
      InsertCommand<Object> insertCommand0 = new InsertCommand<Object>(object0);
      // Undeclared exception!
      try { 
        insertCommand0.accept((CommandVisitor<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.text.diff.InsertCommand", e);
      }
  }
}
