/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 10 17:40:21 GMT 2024
 */

package org.apache.commons.text.diff;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.text.diff.KeepCommand;
import org.apache.commons.text.diff.ReplacementsFinder;
import org.apache.commons.text.diff.ReplacementsHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class KeepCommand_ESTest extends KeepCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-128));
      KeepCommand<Integer> keepCommand0 = new KeepCommand<Integer>(integer0);
      KeepCommand<Object> keepCommand1 = new KeepCommand<Object>(keepCommand0);
      ReplacementsFinder<Object> replacementsFinder0 = new ReplacementsFinder<Object>((ReplacementsHandler<Object>) null);
      replacementsFinder0.visitDeleteCommand(integer0);
      // Undeclared exception!
      try { 
        keepCommand1.accept(replacementsFinder0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.text.diff.ReplacementsFinder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-128));
      KeepCommand<Integer> keepCommand0 = new KeepCommand<Integer>(integer0);
      KeepCommand<Object> keepCommand1 = new KeepCommand<Object>(keepCommand0);
      ReplacementsFinder<Object> replacementsFinder0 = new ReplacementsFinder<Object>((ReplacementsHandler<Object>) null);
      keepCommand1.accept(replacementsFinder0);
  }
}
